name: contactapp
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
flutter:
  uses-material-design: true

environment:
  sdk: '>=3.1.0-262.0.dev <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  material_design_icons_flutter: ^7.0.7296
  cupertino_icons: ^1.0.2
  contacts_service: ^0.6.3
  permission_handler: ^11.0.1
  flutter_contacts: ^1.1.7+1
  url_launcher: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
